### ISSUE TITLE
resty.jwt required even when not needed

### ISSUE THREAD

**Issue by joshku** [zmartzone/lua-resty-openidc#124]
Hi,

In the readme it says 

>If you run as an OAuth 2.0 Resource Server and your access tokens are JWT bearer tokens and you want to verify those tokens locally (no external callouts required, see 2nd configuration example below), you need to install two more pure-Lua dependencies:
    lua-resty-jwt
    lua-resty-hmac

Yet if I do not run my nginx as a resource server and I do not use JWT bearer tokens, theoretically I should not have to install these lua dependencies but when I startup the NGINX server, I get an error like this

```
2017/11/17 21:00:30 [error] 103#103: *5729 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/openidc.lua:54: m
odule 'resty.jwt' not found:
```
That file is is in the Lua dependencies but I do not require them for what I am using yet it seems to be calling those libraries. Is there a way to bypass this if we do not require these dependencies?

**Comment by zandbelt** [comment]
I believe we should indeed improve this situation by putting the `require "resty.jwt` (https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L54) statement inside of the two JWT related functions.

**Comment by zandbelt** [comment]
In the mean time I guess the only alternative is to comment out the global require directive.

**Comment by joshku** [comment]
When I tried just adding the required libraries there was also the error

```
2017/11/20 19:49:24 [error] 103#103: *609 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/openidc.lua:571: a
ttempt to concatenate field 'jwks_uri' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/openresty/lualib/resty/openidc.lua: in function 'openidc_pem_from_jwk'
	/usr/local/openresty/lualib/resty/openidc.lua:650: in function 'openidc_load_jwt_and_verify_crypto'
	/usr/local/openresty/lualib/resty/openidc.lua:734: in function 'authenticate'
```

It looks like there are some functions that are already using it whether or not you want to use jwt. Is there other work that needs to be done?

**Comment by bodewig** [comment]
This looks like a different issue (we don't handle the case where discovery doesn't contain a jwks_uri at all. This is a bug.

As for the resty.jwt dependency, this is now also required in order to verify the id token, so I guess the documentation needs to be adapted.

**Comment by zandbelt** [comment]
For OIDC it is required now (as it should be to become a certified implementation) but for the OAuth 2.0 Resource Server only scenario with other-than-JWT tokens, it does not need to be as @joshku correctly points out IMHO.

**Comment by bodewig** [comment]
Has `authenticate` ever worked in a pure OAuth2 setting? https://github.com/zmartzone/lua-resty-openidc/blob/fc764690d43ffbcd24fe9d9909f56c77a2d6ac7e/lib/resty/openidc.lua#L359 in 1.4.1 already assumes there is an id token and it is a JWT and I think that's been the case for a long time.

I believe the only things that have changed are that we now use lua-resty-jwt to parse the JWT instead of doing it ourselves and that we try to verify the signature. There seems to be an id token in @joshku's case.

**Comment by zandbelt** [comment]
I meant to refer to the scenario where `bearer_jwt_verify` is used in an OAuth 2.0 RS config and `opts.discovery` is passed in but no `opt.secret`. Not sure about @joshku case.

**Comment by bodewig** [comment]
Looking at the stack trace there is an RSA signed id token present and the (second) error occurs because the discovery data doesn't contain a jwks_uri. In some of the tests I've been supplying `opt.discovery` as a table, in such a case it can easily happen that there is no jwks_uri.

In the case of no jwks_uri the only thing we could do was to return "we haven't found a key", which I think we should do as a way to make it more robust (a real error message rather than a stack trace).

If I read @joshku's stack trace correctly this would then lead to a case where `authenticate` fails because we fail to verify the id token's signature. I'm not sure whether we want to allow users to disable the signature check or even bypassing the id token verification completely.

In either case we need to adjust the docs to say that users of `authenticate` now have to install lua-resty-jwt as well (which seems to ship with its version of hmac bundled).

**Comment by zandbelt** [comment]
I believe if there's a signature it should validate (if we're able to execute the algorithm) otherwise it may be an indicator of some seriously wrong.

So: 1. adapt docs 2. make jwks_uri detection robust 3. put "require resty.jwt" in JWT functions only ?

**Comment by bodewig** [comment]
looks good to me, are you going to do "2" as well or are you waiting for me (either way is fine by me)

**Comment by zandbelt** [comment]
"2" is in the same branch, I just did not refer to this issue in the commit:
https://github.com/zmartzone/lua-resty-openidc/commit/9752ff096e143a46cb3f56b207953862cb404e4c

**Comment by bodewig** [comment]
will do

**Comment by bodewig** [comment]
done

**Comment by zandbelt** [comment]
merged to master now
