### ISSUE TITLE
Have redirect_uri_path same as path

### ISSUE THREAD

**Issue by blasterspike** [zmartzone/lua-resty-openidc#136]
Hi,
I have a simple question regarding redirect_uri.
Maybe my knowledge on OpenID Connect is very limited but I don't understand the reason for this code
https://github.com/zmartzone/lua-resty-openidc/blob/f63b5e899313aeee482983eb325cf7f252bbdf54/lib/resty/openidc.lua#L1035-L1043
Why can't I have path == opts.redirect_uri_path?

Here it is an example of my location block:

```
location ~/([a-z\-]+)/([0-9\-]+)/(.*)/?$ {
    set $application $1;
    set $port $2;
    set $req_query_string $3;

    access_by_lua_block {

        local opts = {
           redirect_uri_path = "/" .. ngx.var.application .. "/" .. ngx.var.port .. "/" .. ngx.var.req_query_string,
           discovery = "https://example.com/adfs/.well-known/openid-configuration",
           client_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxx",
           client_secret = "xxxxxx",
           ssl_verify = "no",
           scope = "openid allatclaims"
        }

        -- call authenticate for OpenID Connect user authentication
        local res, err = require("resty.openidc").authenticate(opts)

        if err then
          ngx.status = 500
          ngx.say(err)
          ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
        end

        user_allowed = false
        for key, value in pairs(res.id_token.group) do
          if value == "mydomain\\Support Team" then
             user_allowed = true
          end
        end

        if user_allowed == false then
          return ngx.exit(ngx.HTTP_FORBIDDEN)
        end
    }

    proxy_connect_timeout   1;
    proxy_send_timeout      1;
    proxy_read_timeout      15;

    proxy_http_version 1.1;
    proxy_set_header Connection close;

    proxy_buffer_size 8k;

    proxy_set_header Proxy "";

    proxy_pass $url_of_my_application;
}
```

As the location block is pretty specific, I would like the user to be redirected to the same URL after authentication.
With this configuration, I'm getting back the error

` authenticate(): request to the redirect_uri_path but there's no session state found`

The goal of using openidc is to protect specific endpoints and not redirect users somewhere else, that's why the need to have path = opts.redirect_uri_path

Thanks

Massimo Vannucci

**Comment by zandbelt** [comment]
The goal of OpenID Connect is to establish user identity via a Provider to which the user's browser is redirected. In order to communicate back to the Client i.e lua-resty-openidc, the Provider redirects to a callback URI (the so-called "Redirect URI"). That URL requires special handling of the authentication response from the Provider and creating a session; as such the Redirect URI is an exception to regular processing.

You will be redirected to the original URL as that's part of the state that is kept by lua-resty-openidc.

Theres an issue with your config: you should replace `redirect_uri_path` with a fixed path like `/callback` and not a dynamic URL. As specified in the README you should then register the full Redirect URI `ngx.var.scheme.."://"..ngx.var.http_host..opts.redirect_uri_path` with the Provider.
