### ISSUE TITLE
Configure IDP Metadata without discovery endpoint

### ISSUE THREAD

**Issue by SirElectro** [zmartzone/lua-resty-openidc#191]
Hi, 
the module mod_auth_openidc supports endpoint configuration without OIDC discovery. 
I don't find any information about manual configuration for this module. 
Is it possible to use the nginx version without discovery, too? 

Best regards, 

Chris

**Comment by zandbelt** [comment]
It is not documented but you can set `opts.discovery` to a JSON document with OP configuration information instead of a Discovery URL. The JSON document must still follow the Discovery syntax from http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata but is now provided statically by the RP config instead of retrieved dynamically from the OP.
