### ISSUE TITLE
Azure AD integration doesn't verify access token signature

### ISSUE THREAD

**Issue by jonasgrunert** [zmartzone/lua-resty-openidc#274]
Thanks for the awesome package first off. Until now I used Keycloak, but we are moving to Azure AD now and for no particular reason the jwts in the access_token does not get verified anymore.

### Environment

- lua-resty-openidc version: 1.7.1
- OpenID Connect provider: Azure AD 

###### Expected behaviour

I am sending an access token I obtained from the Azure AD in the Authorization Header with Bearer <Access_Token>. I expect the token to be verified using the given discovery endpoint.
The id_token can be used and verified.

###### Actual behaviour

The id_token can be used and verified. But the access token is revoked with `jwt signature verification failed: Verification failed`.

###### Minimized example
```
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;
# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;
error_log /dev/stdout;
events {
    worker_connections 1024;
}
http {
    lua_package_path '/usr/local/openresty/lualib/?.lua;;';
    lua_ssl_verify_depth 2;
    lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.pem;
    ssl_trusted_certificate /etc/ssl/certs/ca-certificates.pem;
    resolver 8.8.8.8;
    include /etc/nginx/conf.d/*.conf;
    # cache for discovery metadata documents
    lua_shared_dict discovery 1m;
    # cache for JWKs
    lua_shared_dict jwks 1m;
    index   index.html index.htm;
    server {
        listen                443 ssl;
        listen                80 default_server;
        # ssl_certificate       cert.crt;
        # ssl_certificate_key   privkey.pem;
        root                  /var/www/html;
        client_max_body_size  8M;
        # I disabled caching so the browser won't cache the site.
        expires               0;
        add_header            Cache-Control private;

        location / {
          if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Headers' 'Authorization';
            return 204;
          }
          access_by_lua '
            local openidc = require("resty.openidc")
            openidc.set_logging(nil, { DEBUG = ngx.INFO })
            local opts = {
                redirect_uri_path = "https://oidcdebugger.com/debug",
                discovery = "https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration",
                client_id = "my client-id",
                redirect_uri_scheme = "https",
                logout_path = "/logout",
                session_contents = {id_token=true, access_token=true}
            }
            -- call introspect for OAuth 2.0 Bearer Access Token validation
            local res, err = require("resty.openidc").bearer_jwt_verify(opts)
            if err then
              ngx.status = 500
              ngx.say(err)
              ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
            end
            if res then
              ngx.status = 200
              ngx.say(res.unique_name)
            end
          ';
        }
    }
}
```

###### Configuration and NGINX server log files
Logs:  
192.168.99.1 - - [04/Jul/2019:15:15:19 +0000] "GET / HTTP/1.1" 500 66 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
2019/07/04 15:16:19 [alert] 6#6: ignoring stale global SSL error (SSL: error:04091068:rsa routines:INT_RSA_VERIFY:bad signature)

**Comment by jonasgrunert** [comment]
Found the follwing [explanation](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/609), therefore closing this. It is not upon this libary to validate the access_token.

**Comment by cirix** [comment]
Hi team,
first of all great effort you are putting in. On this topic, you are stating the the intro() library introduced is not mend for that? From the "explanation" the only thing I can deduct is that AAD is simply not fully OAuth 2.0 compliant as it doesn't offer and introspection endpoint.
Do you have any proposal on how to take it forward?

kr
Nik

**Comment by bodewig** [comment]
please forgive my ignorance, but I have no idea what the intro() library may be :-)

The original ticket says the access token has not been signed by a key that AAD uses for signing id tokens. Given that neither OAuth2 nor OpenID Connect require the access token to be a signed JWT at all, this is perfectly fine - unless AAD claims to do something else.

The linked AAD discussion says that you are not supposed to verify the access token as you are not the intended recipient (audience in OAuth2 lingo) of the token. The token is meant for the Graph API and only the Graph API - and it knows how to validate it. After that the whole discussion takes strange turns that I didn't follow.

TBH I don't know whether AAD offers an introspection endpoint or not. The introspection endpoint is defined in a separate RFC from the OAuth2 framework. So whether AAD is OAuth2 compliant or not is completely unrelated to the question of an introspection endpoint. This issue doesn't talk about introspection endpoints either, BTW.

**Comment by jonasgrunert** [comment]
To chip in as the original creator. @bodewig is completely right in the regard that AAD does everything according to specification. As the access token ist not meant to bei verified by the non target audience all is fine.   For further questions I might help, but I would need to undestand the use-case better.

**Comment by cirix** [comment]
Hi both,
 the use case is a typical client credentials flow for machine to machine communication with preauth using open resty + AAD.  I should correct the title to give better context, but as such the use case I have:

- Application A run client credentials flow against AAD => app gets an access token from AAD
- Application A invokes  API behind OpenResty
- OpenResty now needs to validate the token to allow or disallow the traffic to pass through
On the mentioned discussion I have fundamental disagreement , and of course Microsoft is positioning itself as it prefers in order to stop the discussion. But again is not the point. RFC7662 defines an extension to the original OAuth 2.0 RFC introducing the introspecting endpoint. Is similar extension to the introduction of PKCE. So it's considered part of the OAuth 2.0 standard, and to be more accurate and improvement.
In my case I don't want to use any Graph API or other tokens, in which point the mentioned article do make sense. My use case is the usage of AAD, and the part of it called Microsoft Identity Platform to be used as IdP. I hope now the use case is clear. 
It boils down to:
- Microsoft is not supporting the introspection endpoint
- There is a capability thow to validate jwt tokens as it offers such endpoint
Are the above use cases considered and are you aware if anyone from the community has managed to reach out. Going through the github page not much. I only found a fork of your effort(btw fucking awesome job guys), that is incomplete. I am not a lua developer but I think AAD is getting more and more traction and your voice would be great addition on Microsoft to implement the extension of the standard. Open to discuss that also over some irc channel. I would also chip in if needed it on the devel side. 

kr
Nik
