### ISSUE TITLE
Question: How do I implement front-channel logout?

### ISSUE THREAD

**Issue by jnivala** [zmartzone/lua-resty-openidc#308]
I am using Lua-resty-openidc as an RP (Open ID Connect Client). My OP is IdentityServer v4.

How do I implement front channel logout? I have multiple applications that authenticate against the OP. When user logs out from any of them, I wish the remaining clients to log out automatically, too.

IdentityServer allows me to specify FrontChannelLogoutUri. Is there a way to configure this in Lua-resty-openid or do I need to implement this by myself?

**Comment by bodewig** [comment]
Right now there is no support for any of the OP initiated logout specs.

Implementing front-channel logout shouldn't be too difficult because all we'd really have to do was to destroy the session if I understand the spec correctly.

Even without lua-resty-openidc supporting it directly you should be able to add a `content_by_lua_block` to a location of your choice which basically does a 

```
    local s, is_existing = require 'resty.session'.open()
    if is_existing then
      s:destroy()
    end
    ngx.header["Cache-Control"] = "no-cache, no-store"
    ngx.header.content_type = "text/html"
    ngx.print('<html></html>')
```

Of course I may be overlooking something. At least we should verify the token we have stored inside of the session has been issued by the `iss` and matches the `sid` given to avoid rogue logouts by third parties.

If we wanted to find the session based on `sid` and not assume we know the current user session via a cookie stored inside of the browser then things may become more difficult.

Also the browser must be willing to send the cookie when loading the iframe which may require proper `SameSite` settings depending on your browser.

**Comment by jnivala** [comment]
Thanks, that worked!

For reference:
Request issuer is escaped. It can be unescaped this way:
`ngx.unescape_uri(ngx.var.arg_iss)`

Identityserver sends lower case url of itself as issuer.

Request sid is here:
`ngx.var.arg_sid`

One should probably compare it against session sid that can be found here:
`s.data.id_token.sid` where s is the session as in bodewig's example.
