### ISSUE TITLE
Integration with Azure AD - cookies not written even after successful authentication and token generation

### ISSUE THREAD

**Issue by anishnagaraj** [zmartzone/lua-resty-openidc#364]
I am using lua-resty-openidc for one of our web applications developed for a big firm in Germany. I integrate lua-resty-openidc with Azure AD. The details of the issue I am facing are as follows.

###### Environment

- lua-resty-openidc version - 1.7.3
- OpenID Connect provider - Azure AD

###### Expected behaviour

The request from my webapplication is forwarded to the LUA OpenID library(lua-resty-openidc) that will verify that the request contains the following cookies: 'session', 'session_2' and optional 'session_3' cookie or a special parameter named 'code', containing the authorization data generated by the Microsoft Authentication endpoint
    - if the cookies or the 'code' parameter are not in the request:
        - the user will be redirected to the Microsoft Authentication endpoint defined in the LUA OpenID configuration table with a callback URL parameter (defined in the LUA OpenID configuration table)
        - after the user will be authenticated against the Microsoft Authentication endpoint it will be redirected with the 'code' parameter to the callback URL and if the 'code' parameter is valid, the LUA OpenID library will set the cookies 'session', 'session_2' and the optional one 'session_3'
        - the request is forwarded to the upstream corresponding to the path
    - if the cookies or the 'code' parameter are present they will be validated and decrypted by the LUA OpenID library

###### Actual behaviour

This behaviour is not for all users. For few uses especially mobile users, are getting into a redirect loop. After these users are authenticated against the Microsoft Authentication endpoint the 'code' parameter to the callback URL is also generated, but the lua-resty-openidc is not setting the cookies 'session', 'session_2' and the optional one 'session_3'. The request gets stuck right there and hence the redirection to the upstream url is not happening.

The problem is the module doesn't throw an error message which would be helpful to debug.

###### Minimized example

```
set $session_secret "#SESSION_SECRET#"; # used for OpenID authentication in the lua-resty-openidc library
        access_by_lua_block {
            local args = ""
            if ngx.var.args ~= nil then args="?"..ngx.var.args end
            if dev then ngx.log(ngx.INFO, "Entered script with path: "..ngx.var.path.." and args: "..args) end

            if ngx.var.path == "index.html" then
              ngx.redirect("#DEFAULT_URL#", 301)
            end
            local domain_sufix = '.#K8S_NAMESPACE#.svc.cluster.local'
            local b64 = require "base64"
            local cjson = require "cjson"
            local oidc = require("resty.openidc")
            local curl = require "cURL"
            local opts = {
                redirect_uri = "/secured",
                discovery = "https://login.microsoftonline.com/#AZURE_TENANT_ID#/v2.0/.well-known/openid-configuration",
                client_id = "#AZURE_SP_ID#",
                client_secret = "#AZURE_SP_SECRET#",
                ssl_verify = "no",
                scope = "#AZURE_OPENID_SCOPE# openid email profile",
                accept_unsupported_alg = false,
                session_contents = {enc_id_token=true, access_token=true, id_token=true },
                use_nonce = false,
            }
            local res, err = oidc.authenticate(opts)

            ngx.log(ngx.INFO, "Authenticated...")
```

**Comment by anishnagaraj** [comment]
I think I was able to distinguish the scenarios where the chunked cookies work and where it doesn't work. 
To begin with, I cleared my cookies and singed into the application again. I have two different accounts with which I can sign in.

With my first account, I have no issues at all. The flow is very smooth. I have about 10 different pages in my application and the navigation between all these pages work absolutely fine.

With my second account, I am able to successfully sign in and land on apage but from then on, I am unable to navigate to other links in my application.

When I compare the chucked cookies, for my first account, I just have three chunks which are `session, session_1 and  session_2
`
Whereas for my second account the number of chunks is four. `session, session_1,  session_2 and session_3`

So my observation is whenever there are more than 3 chunks, the library is unable to validate it successfully. 

My other observation is, when the user signs-in through mobile, the user gets stuck with the redirection loop right in the sign-in

Unfortunately, this issue showed up only after we went live. We realized the issue only after users started complaining. So any help at the earliest is much appreciated.

**Comment by bodewig** [comment]
All cookies starting with `session` belong together. If any one of them is missing, the result is the same as if there was no cookie at all. We use lua-resty-session and it shards cookies, as a single cookie can only contain 4000 bytes. If the (encrypted) session state takes more than that, multiple cookies will be used. lua-resty-openidc is not able to realize a cookie of a set of cookies is missing, as lua-resty-session is only telling it "there is no valid session". Something like that  is what you will see inside of the logs.

In you case you are storing a lot in your session and the tokens probably are pretty big themselves. What you describe means you are sending more than 8 or even 12 kB extra data with each request. If there are any reverse proxies in between it is quite possible they have capped the amount of memory they allocate for the headers of a request, limits of 8 or 16 kB are quite common. So maybe a reverse proxy is swallowing cookie headers. 

Whether cookies are being sent has two sides. It could be the server is not sending the correct `Set-Cookie` HTTP headers. Or the browser receives the headers but declines to accept them. There may be browser-imposed limits for the number or size of cookies a server is allowed to set. Some browsers will not accept cookies set for a different origin than the one of the primary page that is loaded at all.

You will have to find out which `Set-Cookie` headers your clients receive and which `Cookie` headers they actually send back with the next requests. You really need to investigate how all cookie related headers pass through all systems that are involved. Most likely you problem is an infrastructure or browser policy issue and not related to lua-resty-openidc directly at all.

If it turns out that the size of your session state is the problem, you should think about reducing the size of the state by storing less data (and/or making the tokens smaller) or switch to a server side session storage.

**Comment by anishnagaraj** [comment]
@bodewig : You are absolutely right. My client(browser) was not setting back all the cookies in the next requests. The problem is with the size of the session cookies. Sometimes the size of the session cookies exceeds 14 kB leaving no room for any application-specific cookies. However, I have now managed to reduce the size of my application-specific cookies and seems to work fine. 

However, the safest option would be is to switch to server-side session storage.  Do you have any references and recommendations for the same?

Thank you so much for your detailed explanation.

**Comment by anishnagaraj** [comment]
@bodewig : Also is there a way to use Session Storage instead of Cookies with lua-resty-openidc

**Comment by bodewig** [comment]
As I wrote, we use https://github.com/bungle/lua-resty-session and you can fully configure it via your nginx config. There are a few choices for server side session storage over there and the best choice depends on your concrete setup and infrastructure that may already be in place.
