### ISSUE TITLE
Support for Single Page Applications?

### ISSUE THREAD

**Issue by rfahlberg** [zmartzone/lua-resty-openidc#391]
###### Environment

- lua-resty-openidc version: 1.7.4
- OpenID Connect provider: Keycloak

###### Question

With mod_auth_openidc there is an option for providing Support for Single Page Applications: [https://github.com/zmartzone/mod_auth_openidc/wiki/Single-Page-Applications#allowing-both-oauth-20-and-openid-connect](https://github.com/zmartzone/mod_auth_openidc/wiki/Single-Page-Applications#allowing-both-oauth-20-and-openid-connect)

Can lua-resty-openidc be configured to achieve the same support for OAuth 2.0 authorization and OpenID Connect authentication on the same endpoints?

**Comment by bodewig** [comment]
there is no built-in way to combine the two, but you should be able to use some custom Lua code that tries `bearer_jwt_verify` first and falls back to `authenticate` if no Bearer token has been presented. Or rather you'd check whether the client sent a Bearer token and use `bearer_jwt_verify` and use `authenticate` otherwise.

**Comment by rfahlberg** [comment]
Thanks for the answer, this is exactly what i did as fallback.
