### ISSUE TITLE
Redirect to url on authentication error?

### ISSUE THREAD

**Issue by b7sus4** [zmartzone/lua-resty-openidc#393]
Hi,

I'm seeing an "request to the redirect_uri_path but there’s no session state found" error on my application so I want to redirect the user to the login page to login again when their session has expired or if the session is still not present after authenticating. Is there a way to achieve this?

I tried adding `ngx.redirect(login_url)` and it does redirect and get rid of the error but causes strange behavior on my application so I feel like I might be missing something. We're using Keycloak as the OIDC provider.

This is a snippet from my conf file:

```

    location / {

       access_by_lua_block{
           local login_url = "http://myurl.com/"

           local opts = {
               redirect_uri_path = "/app",
               discovery = ngx.var.scheme ..
                   "://" .. os.getenv("NGINX_HOSTNAME") .. "/auth/realms/myapp/.well-known/openid-configuration",
               client_id = "nginx",
               client_secret = ngx.var.keycloak_client_secret,
               redirect_uri_scheme = ngx.var.scheme,
               logout_path = "/logout",
               redirect_after_logout_uri = ngx.var.scheme ..
                   "://" ..
                       os.getenv("NGINX_HOSTNAME") ..
                           "/auth/realms/myapp/protocol/openid-connect/logout?redirect_uri=" ..
                               ngx.var.scheme .. "%3A%2F%2F" .. os.getenv("NGINX_HOSTNAME"),
               redirect_after_logout_with_id_token_hint = false,
               session_contents = {id_token = true, access_token = true},
               revoke_tokens_on_logout = true,
               access_token_expires_in = 600
           }

           local oidc = require("resty.openidc")

           local res, err, session = oidc.authenticate(opts)

           if err then
               return ngx.redirect(login_url)
           end

           -- set headers

        }

```

Thank you.

**Comment by bodewig** [comment]
Redirecting to your login URL may not complete the OAuth2 flow involved, I guess.

"request to the redirect_uri_path but there’s no session state found" means your client's browser has navigated the OAuth2 redirect_uri maintained by lua-resty-openids, which should only ever happen if the browser is currently performing an authorization code grant flow or something has gone wrong - like somebody maliciously sending your users that way, or they have just triggered a bug somewhere.

The "no session state found" part means lua-resty-openidc doesn't see its session cookie. If this is a genuine authorization code grant flow then this may happens because the browser refuses to send the cookie. This may happen because of user configuration, browser policy (Safari will never send 3rd party cookies in iframes for example) or because the cookie's SameSite setting doesn't allow it. The latter would happen if your OpenID Connect Provider lives in a different domain than your service and your Cookie was set to SameSite=Strict. You can configure the SameSite setting vial lua-resty-session's configuration.
