### ISSUE TITLE
Questions about the caches

### ISSUE THREAD

**Issue by omasseau** [zmartzone/lua-resty-openidc#407]
Hello, 

I have several questions about the caches : 
- What is exactly the difference between the "introspection" cache and the "jwt_verification" cache ?  I don't really understand the difference between "introspection" and "verification".

- When do entries for each of theses cache expire ? : discovery, jwks, instrospection and jwt_verification.
As I understand for jwks it is 1 day or the value of "jwk_expires_in" if defined
For the introspection cache it is the value of the "exp" claim  or the value of "introspection_interval" if defined
But what about discovery and jwt_verification ?

- How can I determine which cache size I should use ?

Currenly (based on the documentation) I have:

lua_shared_dict discovery 1m;
lua_shared_dict jwks 1m;
lua_shared_dict introspection 10m;
lua_shared_dict jwt_verification 10m;

Is the size a maximum allowed of is it allocated immediately ?
What happens if the cache size becomes bigger thant what is declared ?

Thanks a lot ;)

**Comment by bodewig** [comment]
>  I don't really understand the difference between "introspection" and "verification".

"introspection" happens when you use the `introspect` function. It takes an access token and asks the Authorization Server about its content. See [RFC 7662](https://datatracker.ietf.org/doc/html/rfc7662). The cache is used to store the Authorization Server's response. This doesn't make any assumptions about the structure of the token itself.

"verification" happens when you use the `jwt_verify` function. This assumes the access token is a JWT and verifies it according to the rules of a JWT. The cache is used to store the introspection result. Verification involves cryptographic operations so may be expensive if not cached.

> When do entries for each of theses cache expire ?

This is what I just added to the README

## Caching

lua-resty-openidc can use [shared memory
caches](https://github.com/openresty/lua-nginx-module/#lua_shared_dict)
for several things. If you want it to use the caches, you must use
`lua_shared_dict` in your `nginx.conf` file.

Currently up to four caches are used

* the cache named `discovery` stores the OpenID Connect Disovery
  metadata of your OpenID Connect Provider. Cache items expire after
  24 hours unless overriden by `opts.discovery_expires_in` (a value
  given in seconds) . This cache will store one item per issuer URI
  and you can look up the discovery document yourself to get an
  estimate for the size required - usually a few kB per OpenID Connect
  Provider.
* the cache named `jwks` stores the key material of your OpenID
  Connect Provider if it is provided via the JWKS endpoint. Cache
  items expire after 24 hours unless overriden by
  `opts.jwks_expires_in`. This cache will store one item per JWKS URI
  and you can look up the jwks yourself to get an estimate for the
  size required - usually a few kB per OpenID Connect Provider.
* the cache named `introspection` stores the result of OAuth2 token
  introspection. Cache items expire when the corresponding token
  expires. Tokens with unknown expiry are not cached at all. This
  cache will contain one entry per introspected access token - usually
  this will be a few kB per token.
* the cache named `jwt_verification` stores the result of JWT
  verification.  Cache items expire when the corresponding token
  expires. Tokens with unknown expiry are not cached for two
  minutes. This cache will contain one entry per verified JWT -
  usually this will be a few kB per token.

Many thanks for making me write this :-)
