### ISSUE TITLE
Vulnerability issue - session cookie can still be used after logout

### ISSUE THREAD

**Issue by ShlomitGilo1** [zmartzone/lua-resty-openidc#412]
Hi,
I'm using lua-resty-openidc v1.6.1 for an authorization code flow.
Suppose a user successfully logged in and then logged out, with the session destroyed on logout.
If I copy the session cookie while the user is still logged in and save it, then I can still send requests with the copied session cookie, after user has been logged out, and the requests will pass as authenticated, even though the session has been destroyed!
From debugging the OpenResty code, it turns out that while handling the request with the logged out session cookie, a new session is created as expected, but then the cookie content is copied into this new session without checking first whether this cookie holds a valid session.
This way, the content of the logged out cookie is copied to the new session, and since the 'id_token' and 'authenticated' fields are still valid - the authentication pass successfully and the request is served.
I refer to the following condition in resty/session.lua, session.open(opts) method, which blindly copies the cookie content:

```
    local cookie = getcookie(self)
    if cookie then
        local i, e, d, h = self.storage:open(cookie, self.cookie.lifetime)
        if i and e and e > time() and d and h then
            local k = hmac(self.secret, i .. e)
            d = self.cipher:decrypt(d, k, i, self.key)
            if d and hmac(k, concat{ i, e, d, self.key }) == h then
                d = self.serializer.deserialize(d)
                self.id = i
                self.expires = e
                self.data = type(d) == "table" and d or {}
                self.present = true
                return self, true
            end
        end
    end

```

Thanks.

**Comment by bodewig** [comment]
This is how lua-resty-session seems to work when you use cookies as your session store - and I believe lua-resty-openidc cannot do anything about it.

One way to get around this is to use a different storage. For the other storages only the id is stored inside of the cookie and this will point to nowhere after logout.

Another option is to force a fresh login for critical actions.

**Comment by NitsanMatsliah** [comment]
Hi,
I am working with @ShlomitGilo1 on this issue.
I am having a bit of an issue understanding how this seems to be the way lua-resty-session works when discussing the session of a logged in user.
Assuming I am a user that has logged out, all my session identifiers are supposed to be expired and non reusable.
The current situation allows a malicious user, that has obtained the session of another user (privileged) to use the obtained session to perform action on behalf of that user.
Furthermore, once the privileged session is used (replacing another session identifier in the request), the browser session from here on is the privileged user's session, regardless of any login sequence (not performed).

The code snippet above demonstrates the exact section in the codebase where the issue presents itself -> cookie details of the logged out session are copied to a new session without verifying they are valid and not expired due to a logout action performed. 

I would assume that once a logout action is triggered, the lua-resty-session's codebase would support not only the destruction of the session but also avoid any reuse of the cookie details.

Thanks
Nitsan Matsliah
Application security architect

**Comment by bodewig** [comment]
This is not really the best place to discuss issues you perceive with [lua-resty-session](https://github.com/bungle/lua-resty-session) (/cc @bungle)

AFAICT what you describe only happens if you use the cookie storage for sessions, but if you use a server-side storage for sessions the data used for a session will be completely deleted once the session is destroyed and can not be resurrected later.

If you wanted to achieve the same level of security for a session with the content stored inside of a cookie you'd need to keep a list of destroyed sessions on the backend, which required as much infrastructure on the server side as using a server-side storage does (it might require a bit less of memory, though).

**Comment by omasseau** [comment]
Commenting on this one as I also have the problem.
As we can ask for tokens to be revoked on logout through the 'revoke_tokens_on_logout', wouldn't it be possible to check if the token stored in the session is revoked or not by calling the instrospection endpoint of the OP ?

I guess the problem is knowing when it should be done as calling it the endpoint each time will kill the performances.

**Comment by bodewig** [comment]
> wouldn't it be possible to check if the token stored in the session is revoked or not by calling the instrospection endpoint of the OP

assuming the OP supports token introspection, yes. With only the session available as a way to store when we have last introspected the token this becomes kind of difficult. In the end you end up introspecting the token on each and every request.

lua-resty-openidc provides only limited support if you want to perform something like this in your own Lua code. `openidc.access_token()` will provide you with an existing access token if there is one stored inside the session and `openidc.call_token_endpoint` can be used to invoke the introspection endpoint when parameterized correctly. See the code of `openidc.introspect` which as it is insists on the token to be present in a header or a cookie.
