### ISSUE TITLE
Question : How do you manage protected access to static resources (images, js) ?

### ISSUE THREAD

**Issue by omasseau** [zmartzone/lua-resty-openidc#419]
Hello,

Let's say I have my SPA application webpage at /app.

In nginx I will have this location declared as protected by lua-resty-openidc:

```
location /app {
    access_by_lua_block {
        ...
    }
}
```

So if a user tries to access to http://localhost/app he will be redirected to the idp login page (if he is not logged in or if his session expired)

But how should I manage the static resources like images or js files that are used by my webapp page ?
Ex: 
/app/image1.png
/app/script1.js

If the user session expires and the first request made just after by my webapp is to GET a static resource, like an image, then nginx will return an HTTP 302 response with the 'Location' header set to http://localhost/auth/realms/myrealm/protocol/openid-connect/auth?redirect_uri=/app.

The browser then will not redirect the whole browser tab to the login page but will just display a blank image (I guess it tries to display the content of the login page inside the image region).

So what is the solution to manage static resources that can be fetched dynamically (not loaded when the webapp starts) and make sure the entire browser tab is redirected to the login page if the session has just expired ?

Maybe it is not possible and I should create specific unprotected locations for my static resources ?
Is it a good practice to  leave them unprotected ?

Thanks a lot :)

**Comment by bodewig** [comment]
whether your static resources need to be protected or not is something only you can answer, I'm afraid.

Apart from the option of using separate locations you could also try to identify requests for the static resources inside of you ` access_by_lua_block` and returning ngx.OK instead of invoking `authenticate` (making them effectively unprotected). As for a general recipe it really depends on how you application works. In a classic server rendered web site your user will navigate to a different page and thus trigger a token refresh eventually.

In a JavaScript driven app that loads and then never does a full page load you could periodically try to access a resource and make your access-block return 401s if the token has expired for this specific resource - and have your client do a page reload if it sees a 401.

Much of this can be mitigated by stroing refresh tokens and doing server side token refreshs rather then browser based new login flows. In either case there is no magic recipe that comes with lua-resty-openidc. A solution that works well for you likely ends up using custom Lua and/or JavaScript code and be pretty specific to your setup.
