### ISSUE TITLE
Can't get pem with function openidc_pem_from_jwk

### ISSUE THREAD

**Issue by coderDem** [zmartzone/lua-resty-openidc#476]
Hello,

we have a problem with the function `openidc_pem_from_jwk`. Here we doesn't know what is wrong with our configuration:

` local opts = {
        access_token_expires_leeway = 30,
        accept_none_alg = false,
        accept_unsupported_alg = false,
        renew_access_token_on_expiry = true,
        ssl_verify = "no",
        discovery = {
            jwks_uri = <URL_TO_JWKS>
        }
    }`

`certificate = require("resty.openidc").openidc_pem_from_jwk(opts, kid)`

We get this error:

`2023/04/04 14:26:25 [error] 19#19: *37 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/jwt-lua/resty/nginx-jwt.lua:51: attempt to call field 'openidc_pem_from_jwk' (a nil value)
stack traceback:
coroutine 0:`

###### Environment
- lua-resty-openidc version (e.g. 1.7.6)
- jwks internal entry

Could somebody help here out?
We tested literly everything but stuck.

**Comment by coderDem** [comment]
@bodewig so does it give a way to get only the pem out of the jwks or what is the right way to verify the token from jwks uri?

**Comment by bodewig** [comment]
Let's take a step back and really figure out what you want to do. `openidc_pem_from_jwk` extracts a certificate from a JWK in the PEM format because this is the format that is needed later - but do you really need the certificate in PEM format?

Or do you want to verify a token against the key who's certificate is supposed to be inside of the JWK? In this case you should use `openidc.jwt_verify` which does all the heavy lifting of downloading the JWK and performing the necessary crypto operations.

**Comment by coderDem** [comment]
We want to verify the Bearer Token with the help of the extracted PEM / certificate. We had before the PEM files locally and now we want to use the jwks to load dynamically the PEM file to verify the token. We try the method: `openidc.jwt_verify` out. Thank you.

**Comment by bodewig** [comment]
In the case of a bearer token in an `Authorization` header `openidc.bearer_jwt_verify` may simplify things even further.
