### ISSUE TITLE
Is there any particular reason to use encrypted sessions?

### ISSUE THREAD

**Issue by yordan-lyutskanov** [zmartzone/lua-resty-openidc#483]
I was just wondering if there is any particular reason to use the encrypted resty-session to store access and refresh tokens? Does this extra encryption help in any way?

**Comment by bodewig** [comment]
There are multiple ways to answer this :-) The most easy one could be "lua-resty-session" uses encryption and there is no way to turn it off AFAICS - but that would neither be fair nor completely true as I'd want to encrypt things anyway.

In any case you need to ensure the cookie content you receive really is something you have set yourself. Everybody can send HTTP requests with cookie values just made up and you don't want to trust somebody is logged in just because you receive a cookie header that looks as if the access tokens was present and verified. So the least thing you need to add is some sort of integrity protection of the cookie's value like an HMAC or a cryptographic signature.

Encrypting the cookie provides you with an additional layer of security against attackers who can see your cookie's content. This may be an attacker exploiting a vulnerability in your browser, a machine in the middle attacker reading HTTP content or anybody exploiting of of quite a few other attack vectors present.

If the cookie was not encrypted it might contain the access token which can be used to access services on behalf of the logged-in user. After all lua-resty-openidc implements the authorization code grant flow which (logically) keeps the access token on the server rather than the client. One reason to use this flow is that you don't need to trust the client to keep the token secret and that would be undermined by not encrypting the session.

In the case of the refresh token there is an even stronger case for keeping it secret. While the access token can only be used for a limited time, the refresh token can be used in the future to obtain an access token (and a new refresh token) again and again. Here the attacker would also need the server's client credentials, of course.

Finally the access token (and in particular the id  token when stored inside the session) may contain sensitive information about the logged in user that could be leaked in the case of a successful attack on your user's browser or network infrastructure.

See also https://datatracker.ietf.org/doc/html/rfc6750#section-5 and https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics

**Comment by yordan-lyutskanov** [comment]
Thanks for the info. It totally makes sense. Only thing I don't understand is the following:

Imagine an attacker gains access to my laptop and I have an open session stored in the cookie. The cookie is encrypted but he can steal it and then use it in subsequent requests from another device to pretend he is me. As far as I understand there is nothing in place to stop this. After all the cookie is just a header that will then be decrypted by the server and there is no way for the server to know who actually sent it.

**Comment by bodewig** [comment]
Of course encrypting the cookie doesn't solve all possible attack vectors, I hope I never sounded as if I thought so. If I recall correctly lua-resty-session can optionally tie the cookie to the TLS session so it can only be used for the existing connection, but even that is not save if anybody gets access to the running browser instance and can make it issue requests. The scenario of a stolen cookie used from a different device would be addressed by this. Also the session itself has only got a limited lifetime so replaying the cookie will not be of any value to the attacker anymore at one point in time.

**Comment by yordan-lyutskanov** [comment]
Thanks for the answers. They were really helpful.
