### ISSUE TITLE
Compatibility Issue with lua-resty-openidc and lua-resty-session

### ISSUE THREAD

**Issue by NizanHellman** [zmartzone/lua-resty-openidc#487]
I'm facing compatibility issues while using lua-resty-openidc version 1.7.5 with lua-resty-session. The issue seems to be related to the deprecation of the `session.present` attribute in the latest version of lua-resty-session. I'm using OpenResty version 1.21.4.2-0-jammy.

###### Environment

- lua-resty-openidc version: 1.7.5
- lua-resty-session version: (latest version where session.present was deprecated)
- OpenResty version: 1.21.4.2-0-jammy

###### Expected behaviour

I expected that using lua-resty-openidc 1.7.5 along with the latest version of lua-resty-session in OpenResty 1.21.4.2-0-jammy would work without any compatibility issues.

###### Actual behaviour

When using lua-resty-openidc 1.7.5 with the latest lua-resty-session, I encountered compatibility issues due to the deprecated `session.present` attribute in the latest lua-resty-session version.

###### Minimized example

Steps to Reproduce:
1. Install lua-resty-openidc v1.7.5
2. Use it in conjunction with lua-resty-session (latest)
3. Observe the compatibility issue due to the deprecated `session.present` attribute.

**Comment by bodewig** [comment]
This is a know issue, lua-resty-openidc does not work with lua-resty-session 4.x - and the luarocks spec of 1.7.6 explicitly requires lua-resty-session 2 or 3. See #480

https://github.com/zmartzone/lua-resty-openidc/pull/478 is an initial attempt to make lua-resty-openidc work with lua-resty-session but it turns out to have issues of its own.
